### PR TITLE
Fix/gh failing build

### PR DESCRIPTION
**Pull request by jbpratt78**
Hi @nevi-me , I noticed the GH action was failing to build so I added the component for rustfmt. I then noticed tests failing and #29 so here is the start of integrating Postgres into GH. It is still failing with `relation \"arrow_data\" does not exist"` though but I figured you would know more about how you want to run setup for these tests.

### CODE REVIEW

**Comment by nevi-me** [comment]
Thanks @jbpratt78, I'm more used to Gitlab's CI, so I didn't know how to set this one up properly. Regarding Postgres, is it possible for one to use a custom image as a container? We could then have a test database that's prepopulated with whatever data that's used for tests.

I'll look into it in the interim

**Comment by nevi-me** [comment]
Looks like this fork (https://github.com/danielweller-swp/postgresql-action) of the action you used has init script support. I'll create a SQL script to create/load tables used for tests and come back later today.

**Comment by jbpratt78** [comment]
> Looks like this fork (https://github.com/danielweller-swp/postgresql-action) of the action you used has init script support. I'll create a SQL script to create/load tables used for tests and come back later today.

Great, that is the simplest solution in my opinon! Happy to help. It is possible to create a custom action + container though it requires a bit more work https://help.github.com/en/actions/building-actions/creating-a-docker-container-action

**Comment by nevi-me** [comment]
I've prepared a sql script, do you have an idea of where I should put it?

**Comment by nevi-me** [comment]
It seems like the init script thing isn't working, but it looks like the cause is that the `INPUT_POSTGRESQL_INIT_SCRIPTS` variable is not used. I'll create a custom docker image for the tests

**Comment by jbpratt78** [comment]
> It seems like the init script thing isn't working, but it looks like the cause is that the `INPUT_POSTGRESQL_INIT_SCRIPTS` variable is not used. I'll create a custom docker image for the tests

Hmm interesting, I will play around with it and see what I can find. I do see that [INPUT_POSTGRESQL_INIT_SCRIPTS](https://github.com/danielweller-swp/postgresql-action/blob/master/entrypoint.sh#L11) is being passed into the run command, but it does seem you set the right variable though..

**Comment by jbpratt78** [comment]
And for debugging purposes in the future, [this](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md) is probably the more elegant solution (TIL!)

**Comment by jbpratt78** [comment]
This is very interesting and annoying. We are doing, from what I can tell, exactly the same thing as the example action [here](https://github.com/danielweller-swp/postgresql-action/runs/536004602). Maybe @danielweller-swp can provide some insight.

**Comment by danielweller-swp** [comment]
A problem with the PostgreSQL GA is that the PostgreSQL docker image does not provide a health check. The way I see it, the GA workflow might continue after the PostgreSQL image has been pulled up, but before the init scripts have been applied. A possible (very ugly :-/) workaround might be to `sleep` after the PostgreSQL action.

You could also have a look [here](https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml) which is an alternative way to use PostgreSQL in GA. Seems to be the upcoming "official" way, but I haven't been able to find any docs for it when I last looked into it.

**Comment by danielweller-swp** [comment]
Oops, sorry, looking into it more closely: the docs didn't align with the releases on my fork of the action. `v1` pointed to the version that does not have the init script feature.

I've updated my fork (create a release, update docs) - could you try again with `v2` of the action?

**Comment by nevi-me** [comment]
Thanks @jbpratt78 and @danielweller-swp, tests are passing now. Closes #29

**Pull request merged**
