### PR TITLE
Feature/uniques and histogram

### PR DESCRIPTION
**Pull request by fgadaleta**
Compute histogram (counter of unique elements) in Column and unique values

### CODE REVIEW

**Comment by nevi-me** [comment]
Hey @fgadaleta, may you please clean up some of the commented out lines, so I can review this?

**Comment by fgadaleta** [comment]
added `uniques()` function, now using `noisy_float` to handle `f64` correctly.
Tests added and working.

**Comment by nevi-me** [comment]
The failing test is unrelated, I'll have a look at it separately.

**Comment by fgadaleta** [comment]
> The failing test is unrelated, I'll have a look at it separately.

it's related to `pretty` not being in arrow anymore.

**Pull request merged**
